-- MySQL Script generated by MySQL Workbench
-- Sun May 21 01:11:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 'ovejorest'
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS ovejorest;

-- -----------------------------------------------------
-- Schema ovejorest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ovejorest` DEFAULT CHARACTER SET utf8 ;
USE `ovejorest` ;

-- -----------------------------------------------------
-- Table `ovejorest`.`quienes_somos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`quienes_somos` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`quienes_somos` (
  `idquienes_somos` INT NOT NULL AUTO_INCREMENT,
  `title_quieres_somos` VARCHAR(200) NULL,
  `img` VARCHAR(555) NULL,
  `det_img` VARCHAR(555) NULL,
  PRIMARY KEY (`idquienes_somos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`parrafos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`parrafos` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`parrafos` (
  `idparrafos` INT NOT NULL AUTO_INCREMENT,
  `text_parrafo` VARCHAR(1000) NULL,
  `quienes_somos_idquienes_somos` INT NOT NULL,
  PRIMARY KEY (`idparrafos`, `quienes_somos_idquienes_somos`),
  INDEX `fk_parrafos_quienes_somos_idx` (`quienes_somos_idquienes_somos` ASC),
  CONSTRAINT `fk_parrafos_quienes_somos`
    FOREIGN KEY (`quienes_somos_idquienes_somos`)
    REFERENCES `ovejorest`.`quienes_somos` (`idquienes_somos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `ovejorest`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`menu` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `nombre_menu` VARCHAR(200) NULL,
  `det_menu` VARCHAR(1000) NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`cat_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`cat_menu` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`cat_menu` (
  `idcat_menu` INT NOT NULL AUTO_INCREMENT,
  `nombre_cat_menu` VARCHAR(200) NULL,
  `det_cat_menu` VARCHAR(1000) NULL,
  PRIMARY KEY (`idcat_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`menu_has_cat_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`menu_has_cat_menu` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`menu_has_cat_menu` (
  `menu_idmenu` INT NOT NULL,
  `cat_menu_idcat_menu` INT NOT NULL,
  PRIMARY KEY (`menu_idmenu`, `cat_menu_idcat_menu`),
  INDEX `fk_menu_has_cat_menu_cat_menu1_idx` (`cat_menu_idcat_menu` ASC),
  INDEX `fk_menu_has_cat_menu_menu1_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_menu_has_cat_menu_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `ovejorest`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_cat_menu_cat_menu1`
    FOREIGN KEY (`cat_menu_idcat_menu`)
    REFERENCES `ovejorest`.`cat_menu` (`idcat_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`prod_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`prod_menu` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`prod_menu` (
  `idprod_menu` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NULL,
  `descripcion_producto` VARCHAR(500) NULL,
  `precio_producto` VARCHAR(45) NULL,
  `disponible` INT NULL,
  `calorias_producto` VARCHAR(45) NULL,
  `img_producto` VARCHAR(500) NULL,
  `fecha_creacion_producto` DATE NULL,
  `fecha_modificacion_produccion` DATE NULL,
  PRIMARY KEY (`idprod_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`prod_menu_has_cat_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`prod_menu_has_cat_menu` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`prod_menu_has_cat_menu` (
  `prod_menu_idprod_menu` INT NOT NULL,
  `cat_menu_idcat_menu` INT NOT NULL,
  PRIMARY KEY (`prod_menu_idprod_menu`, `cat_menu_idcat_menu`),
  INDEX `fk_prod_menu_has_cat_menu_cat_menu1_idx` (`cat_menu_idcat_menu` ASC),
  INDEX `fk_prod_menu_has_cat_menu_prod_menu1_idx` (`prod_menu_idprod_menu` ASC),
  CONSTRAINT `fk_prod_menu_has_cat_menu_prod_menu1`
    FOREIGN KEY (`prod_menu_idprod_menu`)
    REFERENCES `ovejorest`.`prod_menu` (`idprod_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prod_menu_has_cat_menu_cat_menu1`
    FOREIGN KEY (`cat_menu_idcat_menu`)
    REFERENCES `ovejorest`.`cat_menu` (`idcat_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`nuestro_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`nuestro_equipo` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`nuestro_equipo` (
  `idnuestro_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_nuestro_equipo` VARCHAR(100) NULL,
  `detalle_nuestro_equipo` VARCHAR(500) NULL,
  PRIMARY KEY (`idnuestro_equipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`personal_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`personal_equipo` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`personal_equipo` (
  `idpersonal_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_personal_equipo` VARCHAR(200) NULL,
  `apellido_p_personal_equipo` VARCHAR(200) NULL,
  `apellido_m_equipo` VARCHAR(200) NULL,
  `cargo_personal_equipo` VARCHAR(200) NULL,
  `descripcion_personal_equipo` VARCHAR(500) NULL,
  `estado_personal_equipo` INT NULL,
  `link_fb_personal_equipo` VARCHAR(500) NULL,
  `link_ig_personal_equipo` VARCHAR(500) NULL,
  `nuestro_equipo_idnuestro_equipo` INT NOT NULL,
  `img_personal_equipo` VARCHAR(500) NULL,
  PRIMARY KEY (`idpersonal_equipo`, `nuestro_equipo_idnuestro_equipo`),
  INDEX `fk_personal_equipo_nuestro_equipo1_idx` (`nuestro_equipo_idnuestro_equipo` ASC),
  CONSTRAINT `fk_personal_equipo_nuestro_equipo1`
    FOREIGN KEY (`nuestro_equipo_idnuestro_equipo`)
    REFERENCES `ovejorest`.`nuestro_equipo` (`idnuestro_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`galeria` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`galeria` (
  `idgaleria` INT NOT NULL AUTO_INCREMENT,
  `nombre_galeria` VARCHAR(200) NULL,
  `descripcion_galeria` VARCHAR(500) NULL,
  PRIMARY KEY (`idgaleria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`img_galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`img_galeria` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`img_galeria` (
  `idimg_galeria` INT NOT NULL AUTO_INCREMENT,
  `nombre_imagen` VARCHAR(200) NULL,
  `link_imagen` VARCHAR(500) NULL,
  `descripcion_imagen` VARCHAR(500) NULL,
  `galeria_idgaleria` INT NOT NULL,
  PRIMARY KEY (`idimg_galeria`, `galeria_idgaleria`),
  INDEX `fk_img_galeria_galeria1_idx` (`galeria_idgaleria` ASC),
  CONSTRAINT `fk_img_galeria_galeria1`
    FOREIGN KEY (`galeria_idgaleria`)
    REFERENCES `ovejorest`.`galeria` (`idgaleria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`ocasion_reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`ocasion_reservas` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`ocasion_reservas` (
  `idocasion_reservas` INT NOT NULL,
  `nombre_ocasion_reservas` VARCHAR(100) NULL,
  `detalle_ocacion_reservas` VARCHAR(200) NULL,
  PRIMARY KEY (`idocasion_reservas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`reservas` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`reservas` (
  `idreservas` INT NOT NULL AUTO_INCREMENT,
  `email_reservas` VARCHAR(100) NULL,
  `nro_contact_reserva` VARCHAR(45) NULL,
  `nro_personas_reserva` INT NULL,
  `fecha_reserva` DATE NULL,
  `hora_reserva` TIME NULL,
  `estado` INT NULL,
  `ocasion_reservas_idocasion_reservas` INT NOT NULL,
  PRIMARY KEY (`idreservas`, `ocasion_reservas_idocasion_reservas`),
  INDEX `fk_reservas_ocasion_reservas1_idx` (`ocasion_reservas_idocasion_reservas` ASC),
  CONSTRAINT `fk_reservas_ocasion_reservas1`
    FOREIGN KEY (`ocasion_reservas_idocasion_reservas`)
    REFERENCES `ovejorest`.`ocasion_reservas` (`idocasion_reservas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`estado_suscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`estado_suscripcion` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`estado_suscripcion` (
  `idestado_suscripcion` INT NOT NULL AUTO_INCREMENT,
  `nombe_suscripcion` VARCHAR(200) NULL,
  `detalle_suscripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idestado_suscripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ovejorest`.`suscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ovejorest`.`suscripcion` ;

CREATE TABLE IF NOT EXISTS `ovejorest`.`suscripcion` (
  `idsuscripcion` INT NOT NULL AUTO_INCREMENT,
  `email_suscripcion` VARCHAR(200) NULL,
  `estado_suscripcion_idestado_suscripcion` INT NOT NULL,
  PRIMARY KEY (`idsuscripcion`, `estado_suscripcion_idestado_suscripcion`),
  INDEX `fk_suscripcion_estado_suscripcion1_idx` (`estado_suscripcion_idestado_suscripcion` ASC),
  CONSTRAINT `fk_suscripcion_estado_suscripcion1`
    FOREIGN KEY (`estado_suscripcion_idestado_suscripcion`)
    REFERENCES `ovejorest`.`estado_suscripcion` (`idestado_suscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
